# Using source code pro fonts
font_family         Source Code Pro Medium
bold_font           Source Code Pro Black
italic_font         Source Code Pro Italic
bold_italic_font    Source Code Pro Black Italic

# Color scheme, following the rest of my config

foreground #ced9d9
background #121717

selection_foreground none
selection_background none

# Black
color0  #222525
color8  #3f4646

# Red
color1  #b84040
color9  #d65e5e

# Green
color2  #408733
color10 #54a147

# Yellow
color3  #bd7b19
color11 #e09f3d

# Blue
color4  #347eb7
color12 #5191c2

# Magenta
color5  #75579e
color13 #8666b3

# Cyan
color6  #228c8c
color14 #31a5a5

# White
color7  #b1b8b9
color15 #dde2e3

background_opacity 1.0

# Disables bell on wrong actions
enable_audio_bell no
