font_family         Source Code Pro Medium
bold_font           Source Code Pro Black
italic_font         Source Code Pro Italic
bold_italic_font    Source Code Pro Black Italic

# Color scheme, following my own Cultured Jet theme

foreground #ced9d9
background #161a1a

selection_foreground none
selection_background none

# black
color0  #212626
color8  #364040

# red
color1  #8c3838
color9  #bf6060

# green
color2  #6c8c38
color10 #8fbf60

# yellow
color3  #bf8f60
color11 #bfbf60

# blue
color4  #386c8c
color12 #608fbf

# magenta
color5  #6d388c
color13 #8f60bf

# cyan
color6  #388c8c
color14 #60bfbf

# white
color7  #919999
color15 #c2cccc

background_opacity 1.0

# Disables bell on wrong actions
enable_audio_bell no
