#!/bin/sh

# -- Application shortcuts --

# Open foot terminal with Super+Shift+Return
riverctl map normal Super+Shift Return spawn kitty

# Run fuzzel with Super+Space
riverctl map normal Super Space spawn fuzzel

# Take screenshots
riverctl map normal Super+Shift S spawn ".config/river/screenshot.sh"

# Spawn file manager
riverctl map normal Super F spawn "kitty 'nnn -P p'"

# -- Window shortcuts --

# Close window with Super+Shift+W
riverctl map normal Super W close

# Exit river with Super+Shift+E
riverctl map normal Super+Shift E exit

# Snap windows with Super+Shift+arrows
riverctl map normal Super+Shift Left snap left
riverctl map normal Super+Shift Right snap right

# Cycle through windows with Super+Tab
riverctl map normal Super Tab focus-view next

# Add media buttons
riverctl map normal None XF86MonBrightnessUp spawn "brightnessctl set +5%"
riverctl map normal None XF86MonBrightnessDown spawn "brightnessctl set 5%-"

riverctl map normal None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
riverctl map normal None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
riverctl map normal None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

# Move windows with Super + LMB
riverctl map-pointer normal Super BTN_LEFT move-view

# Resize windows with Super + RMB
riverctl map-pointer normal Super BTN_RIGHT resize-view

# -- Window rules --

# Make all windows floating
riverctl rule-add float

# Rivertile as default tiler
riverctl default-layout rivertile

# -- Colors and icons --

riverctl background-color 0x2e3440
riverctl border-color-focused 0x4c566a
riverctl border-color-unfocused 0x3b4252
riverctl xcursor-theme "Bibata-Modern-Classic" 

# -- Autostart --

# Start notification daemon with mako
riverctl spawn "mako"

# Make widgets quick by starting eww daemon
riverctl spawn "eww daemon"

# Spawning waybar with simple config
riverctl spawn "waybar -c $HOME/.config/waybar/config -s $HOME/.config/waybar/style.css"

# Setting background with swaybg
riverctl spawn "swaybg -m fill -i $HOME/Pictures/wallpapers/blue-glass.jpg"

# Starting with pipewire for sound
riverctl spawn "pipewire"
