[mgr]
ratio = [0, 1, 1]
sort = "alphabetical"
sort_sensitive = false
sort_dir_first = true
linemode = "mtime"
show_symlink = true

[preview]
wrap = "yes"
tab_size = 4
max_width = 3840
max_height = 3840
image_filter = "triangle"
image_quality = 60

[opener]
play = [
    { run = 'vlc "$@"', orphan = true, for = "unix" }
]
edit = [
    { run = 'zeditor "$@"', orphan = true, for = "unix" }
]
dir = [
    { run = 'yazi "$@"', orphan = true, for = "unix" }
]
open = [
    { run = 'xdg-open "$@"', desc = "Open" }
]

[open]
prepend_rules = [
    { mime = "inode/directory", use = "dir" }
]
