#!/bin/sh

# -- Application shortcuts --

# Open foot terminal with Super+Shift+Return
riverctl map normal Super+Shift Return spawn alacritty

# Run fuzzel with Super+Space
riverctl map normal Super Space spawn fuzzel

# Take screenshots
riverctl map normal Super+Shift S spawn ".config/river/screenshot.sh -s"
riverctl map normal None Print spawn ".config/river/screenshot.sh -f"

# -- Window shortcuts --

# Close window with Super+Q
riverctl map normal Super Q close

# Exit river with Super+Shift+E
riverctl map normal Super+Shift E exit

# Snap windows with Super+Shift+arrows
riverctl map normal Super+Shift Left send-layout-cmd rivertile "main-location left"
riverctl map normal Super+Shift Right send-layout-cmd rivertile "main-location right"

# Cycle through windows with Super+Tab
riverctl map normal Super Tab focus-view next
riverctl map normal Control Tab focus-view next

# Add media buttons
riverctl map normal None XF86MonBrightnessUp spawn ".config/river/overlay.sh brightness up"
riverctl map normal None XF86MonBrightnessDown spawn ".config/river/overlay.sh brightness down"

riverctl map normal None XF86AudioRaiseVolume spawn ".config/river/overlay.sh volume up"
riverctl map normal None XF86AudioLowerVolume spawn ".config/river/overlay.sh volume down"
riverctl map normal None XF86AudioMute spawn ".config/river/overlay.sh volume mute"

# Move windows with Super + LMB
riverctl map-pointer normal Super BTN_LEFT move-view

# Resize windows with Super + RMB
riverctl map-pointer normal Super BTN_RIGHT resize-view

# -- Mouse settings --

# Add natural scrolling
riverctl input touchpad natural-scroll enabled

# Slow touchpad scrolling
riverctl input touchpad scroll-factor 0.5

# Disable middle click on touchpad
riverctl input touchpad middle-emulation disabled

# -- Workspaces --

for i in $(seq 1 5)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags

    riverctl map normal Super+Shift $i set-view-tags $tags
done

# -- Colors and icons --

riverctl background-color 0x2e3440
riverctl border-color-focused 0x4c566a
riverctl border-color-unfocused 0x3b4252
riverctl xcursor-theme "Bibata-Modern-Classic" 

# -- Autostart --

# Start notification daemon with swaync
riverctl spawn "swaync"

# Spawning waybar with simple config
riverctl spawn "waybar -c $HOME/.config/waybar/river.jsonc -s $HOME/.config/waybar/style.css"

# Setting background with swaybg
riverctl spawn "swaybg -m fill -i $HOME/Pictures/wallpapers/blue-dragon.png"

# Add wob pipe
riverctl spawn "mkfifo /tmp/wobpipe && tail -f /tmp/wobpipe | wob"

# -- Window rules --

# Rivertile as default tiler
riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 4 &
